import { jost, poppins } from "@/utils/fonts";
import { Providers } from "../reduxToolkit/provider";
import "./globals.css";
import HeaderSection from "@/components/layout/header/headerSection";
import MenuSection from "@/components/layout/navigation/desktopMenu";
import FooterSection from "@/components/layout/footer/footerSection";
import AwarenessSection from "@/components/layout/footer/awareness/awarenessSection";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${poppins.variable} antialiased`}
      >
        <Providers>
          <HeaderSection />
          <MenuSection />
          {children}
          <FooterSection />
          <AwarenessSection/>
        </Providers>
      </body>
    </html>
  );
}
