import "@/app/globals.css";
import { jost, poppins } from "@/utils/fonts";
import { Providers } from "@/reduxToolkit/provider";
import TopHeader from "@/components/layout/topHeader";
import Menu from "@/components/layout/Menu";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${poppins.variable} antialiased`}>
        <Providers>
          <TopHeader />
          <Menu />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
