import {jost, poppins } from "./fonts";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import Awareness from "@/components/footer/awareness/awareness";
import Navbar from "@/components/header/navbar/navbar";
import Menu from "@/components/header/menu/menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${poppins.variable} antialiased`}
      >
        {/* <Header/> */}
        {/* <Navbar/> */}
        {/* <Menu/> */}
        {children}
        {/* <Footer/>
        <Awareness/> */}
      </body>
    </html>
  );
}
