const IMAGES = {
  LOGO: require("@/assets/logo.png"),
  BANNER: require("@/assets/banner.jpg"),
  MAINBANNER: require("@/assets/main-banner.png"),
  TOPBANNER: require("@/assets/banner-right-top.png"),
  BOTTOMBANNER: require("@/assets/banner-right-bottom.png"),
  GOOGLEPAY: require("@/assets/payment/google-pay.png"),
  MASTERCARD: require("@/assets/payment/mastercard.png"),
  VISA: require("@/assets/payment/visa.png"),
  RUPAY: require("@/assets/payment/rupay.png"),
  APPSTORE: require("@/assets/app/app-store.png"),
  APPGOOGLEPAY: require("@/assets/app/google-pay.png"),
  // Shop Category
  CANCERCARE: require("@/assets/shopcategory/cancer-care.png"),
  ELDERCARE: require("@/assets/shopcategory/elder-care.png"),
  SPECIALCARE: require("@/assets/shopcategory/special-care.png"),
  HEALTHCARE: require("@/assets/shopcategory/health-care.png"),
  HEALTHDEVICECARE: require("@/assets/shopcategory/health-device-care.png"),
  BEAUTYCARE: require("@/assets/shopcategory/beauty-care.png"),
  AYURVEDIC: require("@/assets/ayurvedic.png"),
  // Banner Group
  AROMA: require("@/assets/offers/aroma.png"),
  LABTEST: require("@/assets/offers/labtest.png"),
  HEALTHCAREBANNER: require("@/assets/offers/healthcare.png"),
  AYURVEDICBANNER: require("@/assets/offers/ayurvedic.png"),
  SPECIALCAREBANNER: require("@/assets/offers/specialcare.png"),
  EYECAREBANNER: require("@/assets/offers/eyecare.png"),
  // Our Service and Care
  SHIPPING: require("@/assets/shopcategory/shipping.png"),
  CUSTOMER: require("@/assets/shopcategory/customer-care.png"),
  ANTHROPOLOGY: require("@/assets/shopcategory/anthropology.png"),
  DRUGSTORE: require("@/assets/shopcategory/drugstore.png"),
  EMERGENCY: require("@/assets/shopcategory/emergency-call.png"),
  // Featured Care & Package
  SEASONAL: require("@/assets/featured/seasonal.png"),
  LABPACKAGE: require("@/assets/featured/lab-package.png"),
  CLINICCARE: require("@/assets/featured/clinic-care.png"),
  BABYCARE: require("@/assets/featured/baby-care.png"),
  DRUGCARTS: require("@/assets/featured/drugcarts.png"),
  SPECIALFCARE: require("@/assets/featured/special-care.png"),
  TESTKIT: require("@/assets/featured/test-kit.png"),
  WOMEN: require("@/assets/featured/women.png"),
  // Health Hacks
  HACKS1: require("@/assets/hacks/hacks-1.jpg"),
  HACKS2: require("@/assets/hacks/hacks-2.jpg"),
  HACKS3: require("@/assets/hacks/hacks-3.jpg"),
  // Shop by Category
  FACECARE: require("@/assets/shopbycategory/face-care.png"),
  ORALCARE: require("@/assets/shopbycategory/oral-care.png"),
  NATURALCARE: require("@/assets/shopbycategory/natural-care.png"),
  SKINCARE: require("@/assets/shopbycategory/skin-care.png"),
  GENERIC1: require("@/assets/shopbycategory/generic-1.png"),
  GENERIC2: require("@/assets/shopbycategory/generic-2.png"),
  NEW: require("@/assets/shopbycategory/new.png"),
  BESTSELLER: require("@/assets/shopbycategory/best-seller.png"),
  DISCOUNT: require("@/assets/shopbycategory/discount.png"),
  TRANDING: require("@/assets/shopbycategory/tranding.png"),
  HERBAL: require("@/assets/shopbycategory/herbal.png"),
};

export { IMAGES };
